# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 45m
      tracking-modes: cookie
      
# mybatis
mybatis: 
  mapper-locations: classpath:sqlmap/mappers/**/*Mapper.xml
      
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
    hiddenmethod:
     filter:
       enabled: true
    view:
      prefix: /jsp
      suffix: .jsp   
  # 존재하지 않는 api 요청 처리
    throw-exception-if-no-handler-found: true
  # MYSQL 설정
  datasource: 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://106.10.44.49:3306/bside?characterEncoding=UTF-8&serverTimezone=UTC
#    username: bside
#    password: R6f-q*Jr6u
    
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: sounwoo12!
     
  # 자동 리로드
  devtools:
    livereload: 
      enabled: true
    restart:
      enabled: true

# 메일
mail:
  use-smtp: true
  smtp:
    auth: true
    starttls:
      enable: false
    host: com
    port: 587
  pop3:
    host: 
  from: 
    address: 
    userid: 
    passwd: 