#서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 45m
      tracking-modes: cookie
      
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_name
#    username: username
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver