#서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 45m
      tracking-modes: cookie
      
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    
    
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: goming.team@gmail.com
    password: srvxdrufxzvgobcb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
    hiddenmethod:
     filter:
       enabled: true
    view:
      prefix: /jsp
      suffix: .jsp   
  # 존재하지 않는 api 요청 처리
    throw-exception-if-no-handler-found: true
  datasource: 
    url: jdbc:mysql://49.50.161.32:3306/bside?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: bside
    password: bside
    driver-class-name: com.mysql.cj.jdbc.Driver   

mybatis: 
  mapper-locations: classpath:sqlmap/mapper/**/*.xml
  
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug