#서버 설정
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 45m
      tracking-modes: cookie
      
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    
    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
    hiddenmethod:
     filter:
       enabled: true
    view:
      prefix: /jsp
      suffix: .jsp   
  # 존재하지 않는 api 요청 처리
    throw-exception-if-no-handler-found: true
#  datasource: 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://106.10.44.49:3306/bside?characterEncoding=UTF-8&serverTimezone=UTC
#    username: bside
#    password: bside
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: sounwoo12!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis: 
  mapper-locations: classpath:sqlmap/mappers/**/*Mapper.xml
  
  
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug